defaultSemverRangePrefix: ''

enableGlobalCache: true

nodeLinker: node-modules

npmScopes:
  d3banking:
    npmAuthToken: '${NPM_TOKEN:-}'
    npmRegistryServer: 'https://registry.npmjs.org'

yarnPath: .yarn/releases/yarn-4.4.1.cjs
